### ISSUE TITLE
Passing "detailed_report" in GPTResearcher constructor results in key error

### ISSUE THREAD

**Issue by Handschrift** [assafelovic/gpt-researcher#431]
In Version 0.2.0 detailed reports have been added.

I tried to execute the following code:
```python
report_type = "detailed_report" # using ReportType.DetailedReport.value does not work aswell
researcher = GPTResearcher(query, report_type, config_path="config.json")
await researcher.conduct_research()
report = await researcher.write_report()
```

This code results in a KeyError: 'detailed_report' because the dict in prompts.py (function: "get_report_by_type"):
```python
    report_type_mapping = {
        ReportType.ResearchReport.value: generate_report_prompt,
        ReportType.ResourceReport.value: generate_resource_report_prompt,
        ReportType.OutlineReport.value: generate_outline_report_prompt,
        ReportType.CustomReport.value: generate_custom_report_prompt,
        ReportType.SubtopicReport.value: generate_subtopic_report_prompt
    }
```
does not contain the "detailed_report" key.

Is there another way to execute a research with the "detailed_report" type?

**Comment by assafelovic** [comment]
Fixed here: https://github.com/assafelovic/gpt-researcher/pull/432

**Comment by Handschrift** [comment]
The error still occurs on the master branch. It still throws a KeyError because "report_type_mapping" does not contain the key "detailed_report" or "ReportType.DetailedReport.value"
