### ISSUE TITLE
RETRIVER setting

### ISSUE THREAD

**Issue by peiyaoli** [assafelovic/gpt-researcher#922]
**Describe the bug**
It looks like we cannot set RETRIVER solely to `duckduckgo` or others.

It always throw an exception about `Exception: Tavily API key not found. Please set the TAVILY_API_KEY environment variable.`

**Comment by danieldekay** [comment]
How did you set it?

**Comment by assafelovic** [comment]
Hey @peiyaoli can you try now? I just pushed a fix here: https://github.com/assafelovic/gpt-researcher/pull/924

Please pull latest version

**Comment by ntheodorg** [comment]
the issue is still ongoing, even with using the latest commits

**Comment by assafelovic** [comment]
Did you set RETRIEVER=duckduckgo?

**Comment by ntheodorg** [comment]
i have followed the instructions from https://docs.gptr.dev/docs/gpt-researcher/getting-started/getting-started
There is no information on RETRIEVER and I want to use the default, TAVILY

**Comment by assafelovic** [comment]
You're right there was a bug. Just merged a HUGE PR that also includes a fix for that: https://github.com/assafelovic/gpt-researcher/pull/925

**Comment by assafelovic** [comment]
Please pull and try again

**Comment by assafelovic** [comment]
@ntheodorg can you please update if it's resolved?

**Comment by ntheodorg** [comment]
yup, it solved my observed issue
